name: Lint and Deploy to AWS Lambda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run black code formatter check
      run: black --check .

  deploy:
    # This job will only run if the 'lint' job is successful
    needs: lint
    # Only run on pushes to the master branch, not on pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install only runtime dependencies for the package
        pip install -r requirements.txt --ignore-requires-python
        mkdir -p package
        cp -r src/* package/
        # Manually copy installed packages, excluding linters
        pip install --target=./package -r requirements.txt --ignore-requires-python --no-deps easyocr torch torchvision Pillow requests python-dotenv numpy

    - name: Create deployment zip
      run: |
        cd package
        zip -r ../deploy.zip .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-north-1' # Change to your Lambda's region

    - name: Upload ZIP to S3
      run: aws s3 cp deploy.zip s3://mushrooms-map/deploy.zip

    - name: Update Lambda from S3
      run: |
          aws lambda update-function-code \
            --function-name mushroomsMap \
            --s3-bucket mushrooms-map \
            --s3-key deploy.zip